### ISSUE TITLE
How can I be aware about breaking changes?

### ISSUE THREAD

**Issue by alexcmgit** [halfmage/pixelarticons#10]
I'm currently working in a Dart library `pixelarticons` (not available yet) that helps people to use your wonderful icons inside Flutter apps

I'm creating an script which:
- Download your icons inside `halfmage/pixelarticons/master` in the `/svg` folder
- Then I generate the code from the SVG
- Then I publish the code plus adding +1 to the library version

As you can see the library will be strongly dependant where do you put the icons, so what I want to know is how can I be aware previously that you'll change the folder location (maybe remove the icons from the svg and move somewhere else)

Or if you are not planning to move or change at all

Thanks for your icons, I always use them in my project since they you icons are really well-made and my projects always have the pixel art vibes =)

**Comment by alexcmgit** [comment]
I saw that I can use the releases instead folder SHA, seems to be more stable than the first approach

**Comment by halfmage** [comment]
Hey @lakscastro!

Thanks for asking, but I am not planning to change the location of icons or the icon folder in any time soon.
Happy to hear that you like the icons!

**Comment by alexcmgit** [comment]
Hey @halfmage

Good to know, the package [is now available!](https://github.com/lakscastro/pixelarticons) thanks for your efforts.
