### ISSUE TITLE
Thank you for pixelarticons!

### ISSUE THREAD

**Issue by tipsy** [halfmage/pixelarticons#11]
I know it's not good form to create thank-you issues, but the traffic here wasn't exactly overwhelming, so I thought it was okay. 

I just wanted you to know that everything about this project is top notch. You've made some beautiful icons and a very nice website (the copy functionality is great). You even have CDN links and a Figma project.

Thank you !

**Comment by halfmage** [comment]
Thank you very much @tipsy!

Happy to see that these icons are getting used more and more in other people projects. I am planning to invest some more time into pixelarticons to create new icons and new styles.

**Comment by tipsy** [comment]
It would be nice if there was a way to contribute icons :)

**Comment by halfmage** [comment]
You can send or list any wanted icons as an issue, or send your own creations as screenshots in here.
For now, I still want to be responsible for the quality check and review process.

**But for the future it could be:**

- Create a guide for SVG icon contribution (code guidelines)
- Create a placeholder Figma file where people can create new icons and send them for review.

**Comment by tipsy** [comment]
> For now, I still want to be responsible for the quality check and review process.

Yes, I think this should always be the case. I was thinking more along the line of guidelines. From looking at the icons, these appear to be the rules:

![image](https://user-images.githubusercontent.com/1521451/169155261-b94a0a59-8d7f-4678-b417-a241bea614d6.png)

There are a few exceptions that don't have margins, but most seem to conform to this. With such a small canvas and such a rigid line width, I think some judement calls must be made.

I'd be happy to put together a guideline based on the current icon set if you're interested.

**Comment by tipsy** [comment]
I could program an icon editor for this, that actually sounds kind of fun.

**Comment by halfmage** [comment]
I like this very much!

> There are a few exceptions that don't have margins, but most seem to conform to this. With such a small canvas and such a rigid line width, I think some judement calls must be made.

That's totally true. Since we have very limited space with a 2px stroke-width, sometimes it is just not possible to stay inside the canvas area. I think it would make sense to prepare guidelines for different icon shapes, since this appear in different sizes for the human eye. For example: square, rectangle, circle

As I said: I will have soon more time to get back to Pixelarticons. A documentation would make sense to put on a To-Do List.

**Comment by LichLord91** [comment]
Just wanted to stop in and say thanks for this library. This was EXACTLY what I was looking for.

**Comment by LichLord91** [comment]
Used it last night to modify most of my Docusaurus  searchbar 

![image](https://user-images.githubusercontent.com/8435580/179369183-58f11b69-f71b-4227-9d6b-799e7a9131ae.png)
![image](https://user-images.githubusercontent.com/8435580/179369254-1ec91751-6931-4c32-9f05-2702c23915d1.png)
