### ISSUE TITLE
Icon request: Debug/bug

### ISSUE THREAD

**Issue by tipsy** [halfmage/pixelarticons#12]
Played around a bit, but not really happy with either of them: 
![image](https://user-images.githubusercontent.com/1521451/169159751-655ab2b7-e9fc-4b4e-a0c6-d50d1b945808.png)

**Comment by halfmage** [comment]
Thanks, @tipsy.
Will take care of this soon!

**Comment by halfmage** [comment]
Made four different iterations for a debug/bug icon.

![grafik](https://user-images.githubusercontent.com/1880485/170855876-fc2b0c34-3256-4e19-9cc9-183b45dbe9d8.png)

Will open this here as a little poll:
- [x] Bug 1 (top-left)
- [x] Bug 2 (top-right)
- [ ] Bug 3 (bottom-left)
- [ ] Bug 4 (bottom-right)

**Comment by tipsy** [comment]
I'm not able to vote in your comment, but my ranking is 3, 1, 2, 4 😌

**Comment by halfmage** [comment]
> I'm not able to vote in your comment, but my ranking is 3, 1, 2, 4 😌

Was just a crazy idea to try it with a checkbox list 😁

My favorite would be a mix of 1 & 2.

**Comment by shahmilav** [comment]
Like 1 the best

**Comment by halfmage** [comment]
Made a new commit (https://github.com/halfmage/pixelarticons/commit/7c375e1f3cca7e58a2252c094914076965040c12) with the new icons:

`bug-check` `bug-pause` `bug-play` `bug-stop` `bug` `cellular-signal-0` `cellular-signal-1` `cellular-signal-2` `cellular-signal-3` `cellular-signal-off` `debug-off` `debug` `radio-signal` `radio-tower`

Feel free to check them before I update the NPM package 😊

**Comment by tipsy** [comment]
@halfmage the icons look very nice, but naming appears to be a bit mixed up. The `bug` has as straight mouth, while the `debug` has a curved mouth. The various `bug-check bug-pause bug-play` use `bug` as the base name, but they have curved mouths (`debug` base design).

**Comment by halfmage** [comment]
@tipsy I saw this already, will update it soon!

**Comment by halfmage** [comment]
> @tipsy I saw this already, will update it soon!

Fixed here: https://github.com/halfmage/pixelarticons/commit/2e4df880618fc91d92729e7fa990eb00a6fa9683

I think we are ready to release a new version 😀

**Comment by tipsy** [comment]
Looking forward to it 🥳

**Comment by halfmage** [comment]
Latest release is published. Have fun with 🐞 Icons!

https://github.com/halfmage/pixelarticons/releases/tag/v1.6.0
