### ISSUE TITLE
Icon request: Radio tower and cell phone signal

### ISSUE THREAD

**Issue by tipsy** [halfmage/pixelarticons#13]

**Comment by halfmage** [comment]
Created a couple of different variations to explore where to get with the radio-tower icons.
Cellular-signal icons are pretty abstract and easy to adapt.

![grafik](https://user-images.githubusercontent.com/1880485/170856689-3564f181-ed13-4d37-b922-93007eb3b550.png)

**Comment by tipsy** [comment]
Towers 1 and 2 are my favorites, and the signal-design with bars is a better fit for this icon pack imo. The lower left x is hard to notice when it replaces a bar, maybe you can add it in the top left corner in thst design too?

**Comment by halfmage** [comment]
Thank you for your feedback @tipsy !

- We go with `1` and as a variant with `2` for radio-tower 
- I agree that the bars have a better look for the overall visual of the iconset
- I will move the `states` then to the top-left

**Comment by halfmage** [comment]
Made a new commit (https://github.com/halfmage/pixelarticons/commit/7c375e1f3cca7e58a2252c094914076965040c12) with the new icons:

`bug-check` `bug-pause` `bug-play` `bug-stop` `bug` `cellular-signal-0` `cellular-signal-1` `cellular-signal-2` `cellular-signal-3` `cellular-signal-off` `debug-off` `debug` `radio-signal` `radio-tower`

Feel free to check them before I update the NPM package 😊

**Comment by halfmage** [comment]
All radio and cellular icons are included in the latest release (npm package as well)! Enjoy!

https://github.com/halfmage/pixelarticons/releases/tag/v1.6.0
