### ISSUE TITLE
Why the new released icons are not available within the master/svg folder?

### ISSUE THREAD

**Issue by alexcmgit** [halfmage/pixelarticons#14]
Did I miss something? Someway I can't see the new released icons (`bug-check.svg`, ...) on the master branch inside the svg folder.

Please, let me know, cause the library I built on top this repository can only update if there's all icons available in the location previously mentioned.

Anywy, thanks for the hard work.

**Comment by halfmage** [comment]
Hey @lakscastro !

I checked again, and the new icons are all inside the SVG folder in master.

I changed the wordings for all `bug-...` variants to `debug-...`, so please update. 
https://github.com/halfmage/pixelarticons/blob/master/svg/debug-check.svg

Overview here in this commit: https://github.com/halfmage/pixelarticons/commit/2e4df880618fc91d92729e7fa990eb00a6fa9683

**Following a full list of all the new icons added to 1.6.0:**

`bug`
`debug`
`debug-check`
`debug-off`
`debug-pause`
`debug-play`
`debug-stop`
`radio-signal`
`radio-tower`
`cellular-signal-0`
`cellular-signal-1`
`cellular-signal-2`
`cellular-signal-3`
`cellular-signal-off`

**Comment by alexcmgit** [comment]
Okay I need a pair of glasses.

Thanks for the fast reply. I'll close this issue.
