### ISSUE TITLE
Icon Request: Light/Dark mode icon

### ISSUE THREAD

**Issue by LichLord91** [halfmage/pixelarticons#15]
It'd be cool to have some icons for toggling off/on Light/Dark mode . I see you have a Sun Icon that could work for light mode. Maybe a moon like this for dark mode? 
![image](https://user-images.githubusercontent.com/8435580/179346444-cfdc760b-e512-46d9-bad5-9be823f96428.png)

**Comment by halfmage** [comment]
Hey @LichLord91!
Thank you very much for your request, I will add it to the list for the next release. :)

**Comment by LichLord91** [comment]
Np, here's some additional inspo! 

![image](https://user-images.githubusercontent.com/8435580/179372288-453b1403-1f70-4c14-b896-6e3a267391bf.png)
![image](https://user-images.githubusercontent.com/8435580/179372295-8cc7a779-7309-4fc2-9746-c8ed9b8ec37b.png)
![image](https://user-images.githubusercontent.com/8435580/179372299-b5d037e5-f7cd-456b-98cb-a556dad88ced.png)
![image](https://user-images.githubusercontent.com/8435580/179372304-9f25cddc-fbbe-40d9-98cb-08e68553474d.png)
I'm currently using this one

https://www.svgrepo.com/svg/327904/crescent-moon-light
![image](https://user-images.githubusercontent.com/8435580/179372319-610b766a-73d9-4797-8bc5-084a5e7a1e8a.png)

**Comment by halfmage** [comment]
I created the first iterations for the new icons:

While creating those I had the idea for an alternative icon to the sun icons which should look more natural. In addition to that I added new icons for the combination of sun/moon with the cloud. The new icons would be:

- moon
- moon-star
- moon-stars
- sun-alt
- cloud-sun
- cloud-moon

![grafik](https://user-images.githubusercontent.com/1880485/179390215-1df3dffc-855c-49ed-86f6-2639c65c6e75.png)

Feel free to give me feedback for those icons :)

**Comment by LichLord91** [comment]
I really like the second from the left and the last for the moon. The new sun looks great definitely a great alternative. I can see the old one being good for brightness setting ui and this one for Light mode!

**Comment by halfmage** [comment]
@LichLord91 I just released v1.7.0 with the new icons! The NPM package is updates as well! Have fun!

https://github.com/halfmage/pixelarticons/releases/tag/v1.7.0
