### ISSUE TITLE
Suggestion: font

### ISSUE THREAD

**Issue by marie-bnl** [halfmage/pixelarticons#19]
I would like to use the icons in my polybar

![image](https://user-images.githubusercontent.com/39555268/189546470-61d694b5-3205-45de-b60f-fa8845a877be.png)

It would be nice to provide an icon font

**Comment by halfmage** [comment]
Hey @victorbnl,  that's a great idea!

Can you tell what font size are you using in your polybar?

**Comment by marie-bnl** [comment]
Here the text font (Minecraft) is 15 and the icons font (Material Icons Round) is 16

**Comment by crypnull** [comment]
I would also love this as a font, I want to put it in my waybar which is similar to polybar, this is the font I will be using alongside. https://github.com/IdreesInc/Monocraft

**Comment by marie-bnl** [comment]
I see we're all doing Minecraft themes here ahah. I started making one discovering Monocraft too, but I don't like using monospace fonts in my bar. [Here](https://www.fontspace.com/minecraft-font-f28180) is the non-monospace one I use if you want, available in the Arch User Repository as `otf-minecraft`

**Comment by halfmage** [comment]
## Hello everyone!

Thanks to @Cerallin you can easily create all webfont files with a simple npm command which puts all icons in various webfont formats into a `./fonts/` folder. Just clone the repo and generate the font files. (56de03af8519dbd1fd416a4ba8dcea25dd5769b5)

```bash
npm run font
```
