### ISSUE TITLE
Typo in sort-alphabetic icon

### ISSUE THREAD

**Issue by alexcmgit** [halfmage/pixelarticons#21]
![image](https://user-images.githubusercontent.com/51419598/201763582-41637a1e-f909-45e1-bd06-417d9bbc1d31.png)

May you wanna fix in the next release.

**Comment by halfmage** [comment]
@alexrintt fixed in e941b82. Will be updated with v1.8 release today

**Comment by halfmage** [comment]
🎉 Icon fixed in [v1.8.0](https://github.com/halfmage/pixelarticons/tree/v1.8.0)
