### ISSUE TITLE
Question: What is in the pro? Is it frequently updated?

### ISSUE THREAD

**Issue by bgervan** [halfmage/pixelarticons#26]
Hi, 

is there a screenshot about the icons like in the https://www.majesticons.com/ ?

I see some PRs, are you update this icon set yet or kind of abandoned?

Thanks.

**Comment by fccfc5d245c** [comment]
@bgervan 
Screenshots: https://pixelarticons.com

**Comment by halfmage** [comment]
@bgervan Hey, no it is not abandoned. Just had not enough time, **but that will change soon!**

**Comment by halfmage** [comment]
@bgervan The main difference between the free and the pro set is that you will get all "symbols" (individual icons) in 4 different styles, whereas you only get the default line style (486 symbols) in the free version.

486 symbols x 4 styles = 1.944 icons.

So every time there is a new symbol added we have 4 new icons in summary.
