### ISSUE TITLE
Request: slow, medium, fast, paint bucket, invert, twitter logo

### ISSUE THREAD

**Issue by OKNoah** [halfmage/pixelarticons#3]
Thanks so much, I'm using your icons at my pixel art editor site, https://www.tinyrama.com

I think they would go along with your set well.

**Comment by halfmage** [comment]
Thank you very much for your feedback @OKNoah. I started already with adding your requested icons into the new 1.3.0 release.

**Following a quick preview.** Let me know if you like them or would suggest something else.
![image](https://user-images.githubusercontent.com/1880485/97156536-1ffaa880-1777-11eb-9e96-1a014f293d49.png)

**Comment by halfmage** [comment]
**Icons are published with v1.3.0 release**
https://github.com/halfmage/pixelarticons/releases/tag/v1.3.0

**Comment by OKNoah** [comment]
@halfmage I am at a loss for words.
