### ISSUE TITLE
currentColor missing from icons

### ISSUE THREAD

**Issue by hawkeye64** [halfmage/pixelarticons#9]
There are two icons missing `currentColor` for their stroke, but instead, use `stroke="#000"`. `fill=none` is on both of these, but it'd be nice if they could be configured to the `currentColor` so different icons on the same page have the same look.

They are:
- gift.svg
- sliders-2.svg

I am not sure if it is ok to PR and modify by hand or if the SVGs are generated from elsewhere.

**Comment by halfmage** [comment]
Hey @hawkeye64 !
Thanks for mentioning that, I updated the icons with the last commit: https://github.com/halfmage/pixelarticons/commit/41904b82fd23b61e7d88806420279408b1054d4e

The npm-package will be updated accordingly soon too.

**Comment by hawkeye64** [comment]
Thank you for being responsive. Not a lot of icon set owners are like that, so it's so refreshing. 

If you're curious how your icon set is being used, check out https://iconexplorer.app
